accounts/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.auth.views import login, logout


app_name = 'accounts'

urlpatterns= [

url(r'^$', views.home, name='home'),
url(r'^browse$', views.browse, name='browse'),
url(r'^register/$', views.register, name='register'),
url(r'^login/$',login, {'template_name': 'accounts/login.html'}),
url(r'^logout/$', logout,{'template_name': 'accounts/logout.html'}),
url(r'^(?P<category_id>[0-9]+)/$', views.information, name='information'),
url(r'^category/add/$', views.CategoryCreate.as_view(), name='category-add'),
url(r'^(?P<category_id>[0-9]+)/information/add/$', views.InfoCreate.as_view(), name='information-add'),
url(r'^information/add/$', views.InfoCreate.as_view(), name='information-add'),
url(r'^redirect1/$', views.category_added, name='category_added'),
url(r'^redirect2/$', views.information_added, name='information_added'),
url(r'^(?P<category_id>[0-9]+)/(?P<element_id>[0-9]+)/$', views.description, name='information'),


#surl(r'^browse/$', views., name='browse')

]

cfd2/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout
from accounts.views import home2


urlpatterns = [
    url('^$', home2  , name = 'home_second'),
    url('^admin/', admin.site.urls),
    url('^account/', include('accounts.urls')),

]

accounts/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Category(models.Model):
    category_name = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('accounts:category_added')

    def __str__(self):
        return self.category_name



class Info(models.Model):
    category = models.ForeignKey(Category , on_delete=models.CASCADE)
    title =  models.CharField(max_length=150)
    description = models.CharField(max_length=1000)
    link = models.URLField()

    def get_absolute_url(self):
        return reverse('accounts:information_added')

    def __str__(self):
         return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib. auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):

    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'

        }

        def save(self, commit=True):
            user = super(RegistrationForm, self).save(commit=False)
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.email = self.cleaned_data['email']

            if commit:
                user.save()

            return user

accounts/views.py
from django.shortcuts import render, redirect
from django.views import generic

from django.http import Http404
from django.views.generic.edit import CreateView , UpdateView , DeleteView

from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.forms import UserCreationForm
from .models import Category, Info

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def home(request):
    user = request.user
    context = {'user':user}
    return render(request, 'accounts/home.html' , context)

def home2(request):

    return render(request, 'accounts/home2.html')



def browse(request):
    all_categorys = Category.objects.all()
    context = {'all_categorys':all_categorys}
    return render(request, 'accounts/browse.html', context)


def information(request, category_id):
    try:
        category  = Category.objects.get(pk= category_id)
    except Category.DoesNotExist:
        raise Http404('The Album does not exsit')
    return render(request,'accounts/information.html', {'category': category})


def information_added(request ):

    return render(request,'accounts/redirect2.html')


def category_added(request):

    return render(request,'accounts/redirect1.html')


class CategoryCreate(CreateView):
    model = Category
    fields = ['category_name']


class InfoCreate(CreateView):
    model = Info
    fields = ['title', 'description', 'link', 'category']



def description(request, category_id, element_id):
    category = Category.objects.get(pk = category_id)
    desc = Info.objects.get(pk=element_id)
    context= {'category': category , 'desc': desc}
    return render(request,'accounts/description.html', context)





def register(request):
    if request.method=='GET':
        form = UserCreationForm()
        args = {'form': form}
        return render(request,'accounts/register.html',args)
    else:
        form= UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account/login')

templates/accounts/browse.html
{% extends 'base.html' %}



{% block head %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />

{% endblock %}




{% block body %}





    <h1 class="text-center" style="font-family: 'Abril Fatface', cursive;
    font-size: 40px;">Category List</h1>


    <div class="list-group">
     <div class="container list1">

    {% for category in all_categorys %}
        <a href="/account/{{ category.id }}/" class="list-group-item " >{{ category.category_name }} </a>

    {% endfor %}
         </div>
      </div>



{% endblock %}

templates/accounts/category_form.html
{% extends 'base.html' %}

{% block head %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home_style.css' %}" />

{% endblock %}

 {% block body %}

<div class="container-fluid">
<div class="row">

    <div class="col-sm-12 col-md-9";>
        <div class="panel panel-default" style="margin-left: 30%; margin-top:20%;">
            <div class="panel-body"">

                <form class="form-horizontal" action="" method="post" >
                    {% csrf_token %}
                   {% include  'accounts/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10"></div>
                    <button  type="submit" class="btn btn-success " style="margin-left:140px">Submit</button>
                    </div>
                </form>


            </div>
        </div>
    </div>


</div>
</div>


{% endblock %}

templates/accounts/description.html
{% extends 'base.html' %}



{% block head %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/description.css' %}" />
{% endblock %}









{% block body%}
<h1 class="text-center">{{ desc.title }}</h1>



  <div class="descriptionstyle">
    <p class="card-text">{{ desc.description }}</p>
    <a href="{{ desc.link }}" target="_blank" class="card-link">Visit Link</a>
  </div>
{% endblock %}

templates/accounts/form-template.html
{%  for field in form %}

    <div class="form-group">
        <div class="col-lg-2">
        <span class="text-danger small">{{ field.error }}</span>
        </div>
    <label class="control-label col-lg-2">{{ field.label_tag  }}</label>
    <div class="col-lg-2">{{ field }}</div>



    </div>
{% endfor %}

templates/accounts/home.html
{% extends 'base.html' %}


{% block head %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/button.css' %}" />


{% endblock %}





{% block body%}

<h1 class="text-center">Welcome {{ user.username }}!</h1>
    <h1 class="text-center">Now manage your bookmarks from anywhere around.</h1>


<div class=" text-center" style="margin-top: 9%">
    <a href="/account/category/add" ><button class="btn btn-primary specificbutton">Add Category</button> </a>
    </div>
    <br>

    <div class="text-center">
    <a href="/account/browse"> <button class="btn btn-primary specificbutton">Browse Stuff</button> </a>
    </div>




{% endblock %}

templates/accounts/home2.html
{% extends 'base.html' %}


{% block head %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/button.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/home2.css' %}" />



{% endblock %}





{% block body%}

<h1 class="text-center">Hey! Welcome to CloudMarks!</h1>
 <div class="container">
    <div><h2 class="text-center">Finding it difficult to manage Online Bookmarks?</h2></div>
    <img src="static/accounts/images/book.jpg" width="60%" style="margin-left: 20%; border: 2px; border-radius: 20px">

   <div><h2 class="text-center">Here is the way.</h2></div>

</div>


{% endblock %}

templates/accounts/info_form.html
{% extends 'base.html' %}

{% block head %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home_style.css' %}" />

{% endblock %}

 {% block body %}

<div class="container-fluid">
<div class="row">

    <div class="col-lg-20 col-lg-9";>
        <div class="panel panel-default" style="margin-left: 32%; margin-top:15%;">
            <div class="panel-body">

                <form class="form-horizontal" action="" method="post" >
                    {% csrf_token %}
                   {% include  'accounts/form-template.html' %}
                    <div class="form-group">
                        <div class="col-lg-offset-2"></div>
                    <button  type="submit" class="btn btn-success " style="margin-left:300px">Submit</button>
                    </div>
                </form>


            </div>
        </div>
    </div>
</div>
</div>



{% endblock %}

templates/accounts/information.html
{%  extends 'base.html' %}

{% block head %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/button.css' %}" />


{% endblock %}



{% block body %}


    <h1 class="text-center">{{ category.category_name }}</h1>
    <div class=" text-center">
    <a href="/account/{{ category.id }}/information/add" ><button class="btn btn-primary specificbutton">Add Information</button></a>
    </div>
    <br>

    <div class="list-group ">
     <div class="container list1">

         {% for element in category.info_set.all %}
        <a href = "/account/{{ category.id }}/{{ element.id }}" class="list-group-item">{{ element.title }}</a>
    {% endfor %}

     </div>
    </div>


{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}


{%block head%}
    <title>Login</title>

{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home_style.css' %}" />
{% endblock %}



{% block body %}

    <div class = "container text-center">

<h1 class="text-center">Welcome</h1>

        <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-success" type="submit">Login</button>

    </form>
    </div>
{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}



{%block head%}
    <title>Logout</title>

{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home_style.css' %}" />
{% endblock %}





{% block body %}

    <div class = "container">

<h1 class="text-center">You are now logged out!</h1>


        </div>
{% endblock %}

templates/accounts/redirect1.html
{%  extends 'base.html' %}

{% block head %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/button.css' %}" />


{% endblock %}




{% block body %}

    <h1 class="text-center"> Category Added Succesfully</h1>

    <br>
    <br>
    <div class=" text-center">
    <a href="/account/category/add"> <button class="btn btn-primary specificbutton">Add Another</button> </a>
    </div>
    <br>

    <div class="text-center">
        <a href="/account/browse"><button class="btn btn-primary specificbutton">Browse</button></a>
    </div>

{% endblock %}

templates/accounts/redirect2.html
{%  extends 'base.html' %}


{% block head %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/button.css' %}" />


{% endblock %}






{% block body %}

    <h1 class="text-center"> Information Added Succesfully</h1>

    <br>
    <br>
    <div class=" text-center">
    <a href="/account/information/add"> <button class="btn btn-primary specificbutton">Add More</button> </a>
    </div>
    <br>

    <div class="text-center">
        <a href="/account/browse"><button class="btn btn-primary specificbutton">Browse</button></a>
    </div>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}



{% block head %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home_style.css' %}" />

{% endblock %}


{% block body %}
    <div class=" text-center container">
    <h1> Register Here </h1>
<form method="post">
{% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-success" type="submit">Submit Details</button>

</form>

    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Judson:400,400italic,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Catamaran' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Unkempt' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Seaweed Script' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy" />
    <link href="https://fonts.googleapis.com/css?family=BioRhyme+Expanded" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rammetto+One" rel="stylesheet">



{%block head%}

	<title>Base</title>

{%endblock%}
</head>
<body>



{% if user.is_authenticated %}

<nav class="navbar navbar-inverse">
  <div class="container-fluid">

      <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle= "collapse" data-target = "#topNavBar">
            <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>

           </button>
      <a class="navbar-brand" href="/account/" style="font-family:'Satisfy' , cursive; font-size: 26px; color: white">CloudMarks</a>
      </div>
      <div class="collapse navbar-collapse id = 'topNavBar">
    <ul class="nav navbar-nav">
        <li class="active"><a href="/account"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;Home</a> </li>
    </ul>
          <ul class="nav navbar-nav">
        <li class="active"><a href="/account/browse"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;Browse</a> </li>
         </ul>
    <form class="navbar-form navbar-left" role="search" method = get action="#">
        <div class="form-group">
            <input type="text" class="form-control" name="q" value="">
            <button type="submit" class="btn btn-default">Search</button>
        </div>
    </form>
    <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="/account/category/add"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Stuff</a> </li>

        <li class="active"><a href="/account/logout"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout</a> </li>
    </ul>
</div>
  </div>
    </nav>

{% else %}



<nav class="navbar navbar-inverse">
  <div class="container-fluid">

      <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle= "collapse" data-target = "#topNavBar">
            <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>

           </button>
      <a class="navbar-brand" href="" style="font-family:'Satisfy' , cursive; font-size: 26px; color: white">CloudMarks</a>
      </div>

    <ul class="nav navbar-nav navbar-right">

           <li class="active"><a href="/account/register"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Register</a> </li>
         <li class="active"><a href="/account/login"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Login</a> </li>


    </ul>
</div>
  </div>
    </nav>








{% endif %}


{%block body%}

{%endblock%}



</body>
</html>